package com.alhanpos.store.util

object Constants {
    const val LOGIN = "oauth/token"
    const val DASHBOARD = "api/get-totals"
    const val DASHBOARD_GRAPH = "api/get-dashboard"
    const val LOCATION = "connector/api/business-location"

    //    const val CONTACTLIST = "connector/api/contactapi"
    const val CONTACTLIST = "api/customers"
    const val SUPPLIERLIST = "api/suppliers"
    const val PRODUCTLIST = "connector/api/product"
    const val PAYMENT_ACCOUNTS = "connector/api/payment-accounts"
    const val PAYMENT_METHODS = "connector/api/payment-methods"
    const val UNITSLIST = "api/units"
    const val CATEGORYLIST = "api/categories"
    const val ADDUPDATECATEGORY = "api/category/add"
    const val DELETECATEGORY = "api/category/delete"
    const val BRANDLIST = "api/brands"
    const val ADDUPDATEBRAND = "api/brand/add"
    const val DELETEBRAND = "api/brand/delete"
    const val ADDUPDATEPRODUCT = "api/product/add"
    const val FINALIZEPAYMENT = "api/finalize/payment"
    const val STOCKTRANSFER = "api/stocktransfer"
    const val EXPENSES = "api/expenses"
    const val SELLS = "api/sells"
    const val PURCHASEORDERS = "api/purchaseorders"
    const val STOCKADJUSTMENTS = "api/stockadjustments"
    const val SUBSCRIPTIONS = "api/subscriptions"
    const val ADD_SUPPLIER = "api/supplier/add"
    const val ADD_CUSTOMER = "api/customer/add"
    const val ADD_STOCKTRANSFER = "api/stocktransfer/add"
    const val ADD_STOCKADJUSTMENT = "api/stockadjustment/add"
    const val ADD_PURCHASE = "api/purchase/add"
    const val ADD_EXPENSE = "api/expense/add"
}