package com.alhanpos.store.model.response.product

data class ProductLocation(
    val alternate_number: Any? = null,
    val business_id: String? = null,
    val city: String? = null,
    val country: String? = null,
    val created_at: String? = null,
    val custom_field1: Any? = null,
    val custom_field2: Any? = null,
    val custom_field3: Any? = null,
    val custom_field4: Any? = null,
    val default_payment_accounts: String? = null,
    val deleted_at: Any? = null,
    val email: Any? = null,
    val featured_products: List<String>? = null,
    val id: Int? = null,
    val invoice_layout_id: String? = null,
    val invoice_scheme_id: String? = null,
    val is_active: String? = null,
    val landmark: String? = null,
    val location_id: String? = null,
    val mobile: String? = null,
    val name: String? = null,
    val pivot: Pivot? = null,
    val print_receipt_on_invoice: String? = null,
    val printer_id: Any? = null,
    val receipt_printer_type: String? = null,
    val sale_invoice_layout_id: String? = null,
    val selling_price_group_id: String? = null,
    val state: String? = null,
    val updated_at: String? = null,
    val website: String? = null,
    val zip_code: String? = null
) : java.io.Serializable