package com.alhanpos.store.model.response.contact

import java.io.Serializable

data class ContactData(
    val address_line_1: String? = null,
    val address_line_2: String? = null,
    val alternate_number: String? = null,
    val balance: String? = null,
    val business_id: String? = null,
    val city: String? = null,
    val contact_id: String? = null,
    val contact_status: String? = null,
    val converted_by: String? = null,
    val converted_on: String? = null,
    val country: String? = null,
    val created_at: String? = null,
    val created_by: String? = null,
    val credit_limit: String? = null,
    val crm_life_stage: String? = null,
    val crm_source: String? = null,
    val customer_group_id: String? = null,
    val deleted_at: String? = null,
    val dob: String? = null,
    val email: String? = null,
    val first_name: String? = null,
    val id: Int = 0,
    val is_default: String? = null,
    val is_export: String? = null,
    val landline: String? = null,
    val last_name: String? = null,
    val middle_name: String? = null,
    val mobile: String? = null,
    val name: String? = null,
    val pay_term_number: String? = null,
    val pay_term_type: String? = null,
    val position: String? = null,
    val prefix: String? = null,
    val shipping_address: String? = null,
    val shipping_custom_field_details: String? = null,
    val state: String? = null,
    val supplier_business_name: String? = null,
    val tax_number: String? = null,
    val total_rp: String? = null,
    val total_rp_expired: String? = null,
    val total_rp_used: String? = null,
    val type: String? = null,
    val updated_at: String? = null,
    val total_due: String? = null,
    val zip_code: String? = null
) : Serializable